# Language config
language: node_js
node_js:
  - "node" # Use latest version of Node available

# Cache directories
cache:
  directories:
    - node_modules

# What scripts to run in pipeline
script:
  - ./build/build.sh
  - ./build/test.sh
